### ISSUE TITLE
stats are from every 5 minutes

### ISSUE THREAD

**Issue by mike-kfed** [edg-l/teemasterparser#1]
Hi, I am here due to your great blogpost of efficiently reading the compressed tar archives. Thanks for that one!

In your code on [line 88](https://github.com/edg-l/teemasterparser/blob/1f904042f4640dcc009b9462e733ea0ec51b6b10/src/main.rs#L88) the comment says you are getting data from every 1 minute, but the code picks every 60th file which is every 5th minute. So one of the two, code or comment, needs fixing ;)

**Comment by edg-l** [comment]
fixed
